{% raw -%}
- name: Setup directory permissions for uploads
  file:
    path: "{{ ansistrano_shared_path }}/src/app/uploads"
    state: directory
    mode: 0775
    owner: deploy
    group: www-data
    recurse: true
    follow: yes
{% endraw %}
