version: '2'
services:
    search:
        image: elasticsearch:2.4
        ports:
            - "{{cookiecutter.docker_search_port}}:9200"
    db:
        image: mysql:5
        ports:
            - "{{cookiecutter.docker_db_port}}:3306"
        volumes:
            - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./db/:/var/lib/mysql"
        env_file: "./docker/config/db.env"
        user: "1000:50"
    redis:
        image: redis:3.2
        command: redis-server
        ports:
            - "{{cookiecutter.docker_redis_port}}:6379"
    web:
        build:
            context: .
            args:
                - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
                - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        ports:
            - "{{cookiecutter.docker_web_port}}:80"
            - "{{cookiecutter.docker_web_ssl_port}}:443"
        links:
          - db
          - redis
          - search
        volumes:
            - "./src:/app/src:rw"
            - "./composer.json:/app/composer.json"
            - "./composer.lock:/app/composer.lock"
            - "./config:/app/config"
            - "./vendor:/app/vendor"
            - "./wp-cli.yml:/app/wp-cli.yml"
            - "./docker/config/web.env:/app/.env"
            - "./docker/files/logs:/app/logs:rw"
            - "./docker/files/profiles:/app/profiles:rw"
            - "./docker/files/db-dumps:/app/db-dumps"

