version: '3.1'
services:
    search:
        image: elasticsearch:7.10.1
        ports:
            - "{{cookiecutter.docker_search_port}}:9200"
        environment:
            - discovery.type=single-node

    db:
        image: mariadb:10.4
        ports:
            - "{{cookiecutter.docker_db_port}}:3306"
        volumes:
            - ./docker/files/db-dumps/:/docker-entrypoint-initdb.d/:cached
        env_file: "./docker/config/db.env"

    php-fpm:
        build:
            context: docker/php-fpm
            args:
                - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
                - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        environment:
            XDEBUG_MODE: develop
            XDEBUG_CONFIG: "
                client_host=host.docker.internal
                start_with_request=yes
              "
        working_dir: /app
        volumes:
            - ./src:/app/src:cached
            - ./docker/config/web.env:/app/.env:cached
            - ./vendor:/app/vendor:cached
            - ./config:/app/config:cached
            - ./docker/files/profiles:/app/profiles:delegated
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini:cached

    web:
        image: nginx:alpine
        working_dir: /app
        ports:
            - "{{cookiecutter.docker_web_port}}:80"
            - "{{cookiecutter.docker_web_ssl_port}}:443"
        links:
            - db
            - search
            - php-fpm
        volumes:
            - ./docker/files/certs:/etc/certs:cached
            - ./docker/files/config/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./src:/app/src:cached

    wp-cli:
        image: frojd/wp-cli-php-8.1:latest
        links:
            - db
        volumes:
            - ./src:/app/src:delegated
            - ./wp-cli.yml:/app/wp-cli.yml:cached
            - ./vendor:/app/vendor:cached
            - ./docker/config/web.env:/app/.env:cached
            - ./config:/app/config:cached
            - ./docker/files/db-dumps:/app/db-dumps

    composer:
        image: frojd/composer-php-8.1:latest
        command: install
        volumes:
            - ./src:/app/src
            - ./composer.json:/app/composer.json
            - "./composer.lock:/app/composer.lock"
            - ./docker/config/web.env:/app/.env
            - ./vendor:/app/vendor
